/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.wlasnyprojektzadanie;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author adrik
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        az_jPanel1 = new javax.swing.JPanel();
        az_jLabelGender = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        az_jRadioButtonMen = new javax.swing.JRadioButton();
        az_jRadioButtonWomen = new javax.swing.JRadioButton();
        az_jRadioButtonHel = new javax.swing.JRadioButton();
        az_jLabelIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        az_jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        az_jMenuFile = new javax.swing.JMenu();
        az_jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        az_jMenuEdit = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        az_jMenuHelp = new javax.swing.JMenu();
        Help = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Okno Aplikacji");

        az_jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        az_jLabelGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        az_jLabelGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        az_jLabelGender.setText("WYBIERZ PŁEĆ");
        az_jLabelGender.setToolTipText("");

        az_jRadioButtonMen.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(az_jRadioButtonMen);
        az_jRadioButtonMen.setForeground(new java.awt.Color(255, 255, 255));
        az_jRadioButtonMen.setText("Mężczyzna");

        az_jRadioButtonWomen.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(az_jRadioButtonWomen);
        az_jRadioButtonWomen.setForeground(new java.awt.Color(255, 255, 255));
        az_jRadioButtonWomen.setText("Kobieta");

        az_jRadioButtonHel.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(az_jRadioButtonHel);
        az_jRadioButtonHel.setForeground(new java.awt.Color(255, 255, 255));
        az_jRadioButtonHel.setText("Helikopter Bojowy");

        az_jLabelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        az_jTextArea1.setColumns(20);
        az_jTextArea1.setRows(5);
        jScrollPane1.setViewportView(az_jTextArea1);

        javax.swing.GroupLayout az_jPanel1Layout = new javax.swing.GroupLayout(az_jPanel1);
        az_jPanel1.setLayout(az_jPanel1Layout);
        az_jPanel1Layout.setHorizontalGroup(
            az_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(az_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(az_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(az_jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(az_jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(az_jLabelIcon))
                    .addComponent(jSeparator1)
                    .addGroup(az_jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addGroup(az_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(az_jRadioButtonWomen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(az_jRadioButtonHel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(az_jRadioButtonMen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        az_jPanel1Layout.setVerticalGroup(
            az_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(az_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(az_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(az_jLabelGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(az_jLabelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(az_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(az_jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(az_jRadioButtonMen)
                        .addGap(18, 18, 18)
                        .addComponent(az_jRadioButtonWomen)
                        .addGap(18, 18, 18)
                        .addComponent(az_jRadioButtonHel))
                    .addGroup(az_jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        az_jMenuFile.setText("File");

        az_jMenuItemSave.setText("Zapisz");
        az_jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jMenuItemSaveActionPerformed(evt);
            }
        });
        az_jMenuFile.add(az_jMenuItemSave);

        jMenuItem2.setText("Wczytaj");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        az_jMenuFile.add(jMenuItem2);

        jMenuItem3.setText("Zamknij");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        az_jMenuFile.add(jMenuItem3);

        jMenuBar1.add(az_jMenuFile);

        az_jMenuEdit.setText("Edit");

        jMenuItem4.setText("Zmień tło");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        az_jMenuEdit.add(jMenuItem4);

        jMenuItem5.setText("Zmień czcionke");
        az_jMenuEdit.add(jMenuItem5);

        jMenuBar1.add(az_jMenuEdit);

        az_jMenuHelp.setText("O Programie");

        Help.setText("Help");
        az_jMenuHelp.add(Help);

        jMenuItem6.setText("O programie");
        az_jMenuHelp.add(jMenuItem6);

        jMenuBar1.add(az_jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(az_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(az_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void az_jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jMenuItemSaveActionPerformed
        try{
        
            File f = new File("AZ_Zapis.txt");
            FileWriter fw = new FileWriter(f);
            String zapis = "X";
            if(az_jRadioButtonMen.isSelected()){
                zapis = "Mężczyzna";
            }else if(az_jRadioButtonWomen.isSelected()){
                zapis = "Kobieta";
            }else if(az_jRadioButtonHel.isSelected()){
                zapis = "Helikopter Bojowy";
            }
            fw.write(""+zapis);
            fw.close();
        
        } catch (IOException ex) {
            System.out.print("Błąd: "+e.toString());
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_az_jMenuItemSaveActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
                
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showDialog(this, "AZ_Zapis");
        
        try{
            String text="";
            File f = jFileChooser.getSelectedFile();
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                text = text+sc.nextLine();
            }
            az_jTextArea1.setText(text);                
        } catch (FileNotFoundException ex) {
            System.out.println(ex.toString);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Help;
    private javax.swing.JLabel az_jLabelGender;
    private javax.swing.JLabel az_jLabelIcon;
    private javax.swing.JMenu az_jMenuEdit;
    private javax.swing.JMenu az_jMenuFile;
    private javax.swing.JMenu az_jMenuHelp;
    private javax.swing.JMenuItem az_jMenuItemSave;
    private javax.swing.JPanel az_jPanel1;
    private javax.swing.JRadioButton az_jRadioButtonHel;
    private javax.swing.JRadioButton az_jRadioButtonMen;
    private javax.swing.JRadioButton az_jRadioButtonWomen;
    private javax.swing.JTextArea az_jTextArea1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
